# Site settings
name: Sourav Pati
email: sourav.pati09@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, SpringBoot,Microservices, Apachi Kafka, Elasticsearch,Kubernetties,Serverless,Java,Machine Learning, Deep Learning, Startups, Agile, Pair Programming"
skills: "Senior Software Engineer in Seattle, WA (Fictitious)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sourav-pati-a2909228/
  - title: medium
    url: https://medium.com/@sourav.pati09

    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
